version: '3'
services:
  db:
    image: postgres:17
    container_name: SD_Project
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres  
      - POSTGRES_DB=IEEE_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5435:5432'
  
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: node_app
    ports:
      - '8080:8080'
    depends_on:
      - db 
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/IEEE_db 
volumes:
  pgdata:
